- name: "LAUNCE THE INSTANCES THROUGH ANCIBLE"
  hosts: local
  vars:
    subnetid: subnet-0db7f96b56d8185f0
    secgrpid: sg-0702ac86b9ebe68f7
    amid: ami-09c813fb71547fc4f
    instances:
    - mysql
    - frontend
    - backed
  connection: local
  become: yes
  tasks:
  - name: instances lanch
    amazon.aws.ec2_instance:
      name: "{{item}}""
      vpc_subnet_id: "{{subnetid}}"
      instance_type: "t2.micro"
      security_group: "{{secgrpid}}"
      image_id: "{{amid}}"
    loop: "{{instance}}"
    register: "{{ec2-instances}}"

  - name: print the ec2-instances data
    ansible.builtin.debug:
      msg: "{{ec2-instances}}"


