- name: creating user
  hosts: web
  become: yes
  tasks:
  - name: checking user
    ansible.builtin.command: id expence
    register: USER
    ignore_errors: true

  - name: user is
    ansible.builtin.debug:
      msg: "userid is {{USER}}"
     